### PR TITLE
New cool idea

### PR DESCRIPTION
**Pull request by Thiyaghessan**
Hey thiya! Made cool download function that does cool thing and reduces download speed by 0.5s

### CODE REVIEW

**Review by Thiyaghessan — COMMENTED** [review]
Something's not right, this function doesn't exist

**Comment by Thiyaghessan** [comment]
This won't work because of [reasons]

**Comment by lecy** [comment]
Testing branches?

**Comment by Thiyaghessan** [comment]
Yea showing Hannah how branches work!

**Pull request closed without merging**
